"""Add tipo_evento to Template

Revision ID: 45c3cd58d1fa
Revises: efee194f7dcb
Create Date: 2026-02-19 18:36:45.681305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c3cd58d1fa'
down_revision: Union[str, Sequence[str], None] = 'efee194f7dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('tipo_evento', sa.Enum('quince', 'boda', 'cumple', 'otros', 'infantil', name='tipoeventochoices'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'tipo_evento')
    # ### end Alembic commands ###
