"""init

Revision ID: e6ab3d62cf7e
Revises: 
Create Date: 2026-03-25 20:08:47.332641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ab3d62cf7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('preview', sa.String(length=255), nullable=True),
    sa.Column('tipo_evento', sa.Enum('quince', 'boda', 'cumple', 'otros', 'infantil', name='tipoeventochoices'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_slug'), 'templates', ['slug'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono_envio_confirmacion', sa.String(length=30), nullable=True),
    sa.Column('tipo_evento', sa.Enum('quince', 'boda', 'cumple', 'otros', 'infantil', name='tipoeventochoices'), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=False),
    sa.Column('hora_evento', sa.Time(), nullable=True),
    sa.Column('lugar_evento', sa.String(length=255), nullable=True),
    sa.Column('direccion_evento', sa.Text(), nullable=True),
    sa.Column('fecha_ceremonia', sa.Date(), nullable=True),
    sa.Column('hora_ceremonia', sa.Time(), nullable=True),
    sa.Column('lugar_ceremonia', sa.String(length=255), nullable=True),
    sa.Column('direccion_ceremonia', sa.Text(), nullable=True),
    sa.Column('fuente_nombre', sa.Enum('great_vibes', 'dancing_script', 'allura', 'sacramento', 'parisienne', name='googlefontschoices'), nullable=True),
    sa.Column('mensaje_bienvenida', sa.Text(), nullable=True),
    sa.Column('codigo_vestimenta', sa.String(length=100), nullable=True),
    sa.Column('instagram_url', sa.String(length=300), nullable=True),
    sa.Column('alias_regalos', sa.String(length=100), nullable=True),
    sa.Column('token_acceso', sa.String(length=40), nullable=True),
    sa.Column('mostrar_ceremonia', sa.Boolean(), nullable=False),
    sa.Column('mostrar_galeria', sa.Boolean(), nullable=False),
    sa.Column('mostrar_dresscode', sa.Boolean(), nullable=False),
    sa.Column('mostrar_instagram', sa.Boolean(), nullable=False),
    sa.Column('mostrar_playlist', sa.Boolean(), nullable=False),
    sa.Column('mostrar_regalos', sa.Boolean(), nullable=False),
    sa.Column('imagen_fondo', sa.String(length=255), nullable=True),
    sa.Column('imagen_fondo_ig', sa.String(length=255), nullable=True),
    sa.Column('imagen1', sa.String(length=255), nullable=True),
    sa.Column('imagen2', sa.String(length=255), nullable=True),
    sa.Column('imagen3', sa.String(length=255), nullable=True),
    sa.Column('imagen4', sa.String(length=255), nullable=True),
    sa.Column('imagen5', sa.String(length=255), nullable=True),
    sa.Column('imagen6', sa.String(length=255), nullable=True),
    sa.Column('imagen7', sa.String(length=255), nullable=True),
    sa.Column('imagen8', sa.String(length=255), nullable=True),
    sa.Column('imagen9', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_slug'), 'clientes', ['slug'], unique=True)
    op.create_index(op.f('ix_clientes_token_acceso'), 'clientes', ['token_acceso'], unique=True)
    op.create_table('canciones_playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_interprete', sa.String(length=100), nullable=False),
    sa.Column('nombre_tema', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canciones_playlist_id'), 'canciones_playlist', ['id'], unique=False)
    op.create_table('confirmaciones_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_invitado', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('asistencia', sa.Boolean(), nullable=False),
    sa.Column('cantidad_acompanantes', sa.Integer(), nullable=True),
    sa.Column('restricciones_alimentarias', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmaciones_asistencia_id'), 'confirmaciones_asistencia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmaciones_asistencia_id'), table_name='confirmaciones_asistencia')
    op.drop_table('confirmaciones_asistencia')
    op.drop_index(op.f('ix_canciones_playlist_id'), table_name='canciones_playlist')
    op.drop_table('canciones_playlist')
    op.drop_index(op.f('ix_clientes_token_acceso'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_slug'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_templates_slug'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
