"""Add ceremony details and visibility flags to Cliente

Revision ID: efee194f7dcb
Revises: 
Create Date: 2026-02-18 02:38:13.605710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efee194f7dcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('fecha_ceremonia', sa.Date(), nullable=True))
    op.add_column('clientes', sa.Column('hora_ceremonia', sa.Time(), nullable=True))
    op.add_column('clientes', sa.Column('lugar_ceremonia', sa.String(length=255), nullable=True))
    op.add_column('clientes', sa.Column('direccion_ceremonia', sa.Text(), nullable=True))
    op.add_column('clientes', sa.Column('mostrar_ceremonia', sa.Boolean(), nullable=False))
    op.add_column('clientes', sa.Column('mostrar_galeria', sa.Boolean(), nullable=False))
    op.add_column('clientes', sa.Column('mostrar_dresscode', sa.Boolean(), nullable=False))
    op.add_column('clientes', sa.Column('mostrar_instagram', sa.Boolean(), nullable=False))
    op.add_column('clientes', sa.Column('mostrar_playlist', sa.Boolean(), nullable=False))
    op.add_column('clientes', sa.Column('mostrar_regalos', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'mostrar_regalos')
    op.drop_column('clientes', 'mostrar_playlist')
    op.drop_column('clientes', 'mostrar_instagram')
    op.drop_column('clientes', 'mostrar_dresscode')
    op.drop_column('clientes', 'mostrar_galeria')
    op.drop_column('clientes', 'mostrar_ceremonia')
    op.drop_column('clientes', 'direccion_ceremonia')
    op.drop_column('clientes', 'lugar_ceremonia')
    op.drop_column('clientes', 'hora_ceremonia')
    op.drop_column('clientes', 'fecha_ceremonia')
    # ### end Alembic commands ###
